Add a new language (russian) & add missing ukrainian strings
CloudG360/Survival-Building-Toolkit pull request #21
Opened 2024-11-19 08:25 UTC by Melishy

Glad to contribute it! Just i do speak russian, and i am doing this for russian peoples to understand.
*it's okay if you deny this*

2024-11-19 16:18 UTC, squeeglii requested changes
Russian Translations are great! Thank you for those!
Ukranian Translations - were they particularly inaccurate before? Google Translate gave them the A-Okay last time so I'm a little confused.

2024-11-19 16:18 UTC, squeeglii commented on common/src/main/resources/assets/bridgingmod/lang/ru_ru.json
> +  "config.bridgingmod.option.enableBridgingAssist.description.1": "Это также привязано к привязке клавиш в элементах управления (по умолчанию ",")",
Line is broken at the end by `","`  - use single quote marks `'` inside the translation instead please, or use an escape (`\"`)

2024-11-19 16:18 UTC, squeeglii commented on common/src/main/resources/assets/bridgingmod/lang/uk_ua.json
> +  "key.bridgingmod.toggle_bridging": "Перемкнути перемикання",
The old translation seemed more accurate when translated back to English with Google Translate.
This mentions bridging, right?

2024-11-19 18:46 UTC, Melishy commented on common/src/main/resources/assets/bridgingmod/lang/ru_ru.json
> +  "config.bridgingmod.option.enableBridgingAssist.description.1": "Это также привязано к привязке клавиш в элементах управления (по умолчанию ",")",
oops, my bad! let me fix that.

2024-11-19 18:46 UTC, Melishy commented on common/src/main/resources/assets/bridgingmod/lang/uk_ua.json
> +  "key.bridgingmod.toggle_bridging": "Перемкнути перемикання",
i wasn't having a idea if the mod name was supposed to be translated

2024-11-19 18:48 UTC, Melishy commented on common/src/main/resources/assets/bridgingmod/lang/uk_ua.json
> +  "key.bridgingmod.toggle_bridging": "Перемкнути перемикання",
but some of strings translated to ukrainian are missing from original one, so i decided to

2024-11-19 18:51 UTC, Melishy commented
alright, fixed strings.

2024-11-19 18:56 UTC, Melishy commented
> Russian Translations are great! Thank you for those! Ukranian Translations - were they particularly inaccurate before? Google Translate gave them the A-Okay last time so I'm a little confused as the old ones seem to match better. If you're sure they're 100% accurate to the English, let me know.

It's accurate (and ukrainian translations), because i noticed some strings are missing for translate, like in config, at "Fixes" tab.

2024-11-19 19:49 UTC, squeeglii commented on common/src/main/resources/assets/bridgingmod/lang/uk_ua.json
> +  "key.bridgingmod.toggle_bridging": "Перемкнути перемикання",
oops, my bad. I didn't realise Github selected that.

I'm looking at `key.bridgingmod.toggle_bridging` and how it's changed from "Перемикання мостіння" to "Перемкнути перемикання".

2024-11-20 14:37 UTC, Melishy commented on common/src/main/resources/assets/bridgingmod/lang/uk_ua.json
> +  "key.bridgingmod.toggle_bridging": "Перемкнути перемикання",
hm, alright, i changed it back

2024-11-20 16:26 UTC, merged

2024-11-20 16:26 UTC, squeeglii commented
Thank youuuuuu! :D